source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataBinding_Example', :exclusive => true do
  pod "DataBinding", :path => "../"
end

target 'DataBinding_Tests', :exclusive => true do
  pod "DataBinding", :path => "../"

  pod 'FBSnapshotTestCase'
end
