source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataBinding_Example', :exclusive => true do
  pod "DataBinding", :path => "../"
  pod 'Block-KVO', :git => 'https://github.com/iMartinKiss/Block-KVO.git'
end

target 'DataBinding_Tests', :exclusive => true do
  pod "DataBinding", :path => "../"

  pod 'FBSnapshotTestCase'
end
